#pragma once

static const char *const SSID = "YOUR_WIFI_NAME";
static const char *const PASSWORD = "YOUR_WIFI_PASSWORD";

#define API_KEY "YOUR_FIREBASE_API_KEY"
#define DATABASE_URL "YOUR_FIREBASE_DATABASE_URL"
#define DATABASE_SECRET "YOUR_FIREBASE_DATABASE_SECRET"

#define ALERT_PHONE_NUMBER "YOUR_PHONE_NUMBER"